const equipeData = [
    {
      img: '../assets/img/equipe/c-laporte.png',
      atleta: 'Christophe Laporte',
      equipe: 'Jumbo Visma',
      pais: 'França',
      flag: '../assets/img/flags/fr.svg',
      vitorias: '22',
      podiums:'51',
      profile: 'https://www.strava.com/pros/3834960',
    },
    {
      img: '../assets/img/equipe/d-groenewegen.png',
      atleta: 'Dylan Groenewegen',
      equipe: 'BikeExchange-Jayco',
      pais: 'Holanda',
      flag: '../assets/img/flags/nl.svg',
      vitorias: '68',
      podiums:'120',
      profile: 'https://www.strava.com/pros/4352993',
   
    },
    {
      img: '../assets/img/equipe/h-houle.png',
      atleta: 'Hugo Hole',
      equipe: 'Israel-Premier Tech',
      pais: 'Canadá',
      flag: '../assets/img/flags/ca.svg',
      vitorias: '3',
      podiums:'15',
      profile: 'https://www.strava.com/pros/288769',
 },
    {
      img: '../assets/img/equipe/j-philipsen.png',
      atleta: 'Jasper Philipsen',
      equipe: 'Alpecin-Deceuninck',
      pais: 'Bélgica',
      flag: '../assets/img/flags/be.svg',
      vitorias: '32',
      podiums:'81',
      profile: 'https://www.strava.com/pros/1727324',
    },
    {
      img: '../assets/img/equipe/j-vingegaard.png',
      atleta: 'Jonas Vingegaard',
      equipe: 'Jumbo Visma',
      pais: 'Dinamarca',
      flag: '../assets/img/flags/dk.svg',
      vitorias: '10',
      podiums:'32',
      profile: 'https://www.strava.com/pros/10495058',
    },
    {
      img: '../assets/img/equipe/m-matthews.png',
      atleta: 'Michael Matthews',
      equipe: 'BikeExchange-Jayco',
      pais: 'Austrália',
      flag: '../assets/img/flags/au.svg',
      vitorias: '48',
      podiums:'133',
      profile: 'https://www.strava.com/pros/2468821',
   
    },
    {
      img: '../assets/img/equipe/t-pogacar.png',
      atleta: 'Tadej Pogacar',
      equipe: 'UAE Team Emirates',
      pais: 'Eslováquia',
      flag: '../assets/img/flags/sk.svg',
      vitorias: '48',
      podiums:'87',
      profile: 'https://www.strava.com/pros/6021015',
    },
    {
      img: '../assets/img/equipe/w-van-aert.png',
      atleta: 'Wout Van Aert',
      equipe: 'Jumbo Visma',
      pais: 'Bélgica',
      flag: '../assets/img/flags/be.svg',
      vitorias: '35',
      podiums:'76',
      profile: 'https://www.strava.com/pros/189040',
    },
    {
      img: '../assets/img/equipe/y-lampaert.png',
      atleta: 'Yves Lampaert',
      equipe: 'Quick-Step Alpha Vinyl',
      pais: 'Bélgica',
      flag: '../assets/img/flags/be.svg',
      vitorias: '21',
      podiums:'54',
      profile: 'https://www.strava.com/pros/2916067',
    },
  ];

  module.exports = {
    equipeData,
  };
  